sudo: required
language: bash

services:
  - docker

notifications:
  email:
    recipients:
      - blue_tie@hotmail.com
    on_success: never
    on_failure: never


env:
  - SPARK_VERSION=2.4.7

before_script:
  - env | grep TRAVIS_ > travis.env
  - echo "CI_NAME=travis_ci" >> travis.env
  - echo "CI=true" >> travis.env
  - echo "TRAVIS=true" >> travis.env
  - echo "CONTINUOUS_INTEGRATION=true" >> travis.env
  - echo "DEBIAN_FRONTEND=noninteractive" >> travis.env
  - echo "HAS_JOSH_K_SEAL_OF_APPROVAL" >> travis.env
  - echo $SPARK_VERSION >> travis.env

script:
  - docker build -t includes/sparklet:$SPARK_VERSION .
  - docker run --env-file travis.env -v $(pwd):/opt/src --workdir="/opt/src" --rm includes/sparklet:$SPARK_VERSION ./testpyt.py


