#!/usr/bin/with-contenv ash

echo "spark.master  spark://$HOSTNAME:7077" > /opt/spark-2.4.7-bin-hadoop2.7/conf/spark-defaults.conf

exec /opt/spark-2.4.7-bin-hadoop2.7/bin/spark-class org.apache.spark.deploy.master.Master --ip $HOSTNAME --port 7077 --webui-port 8080
